name: TikTok API Request

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  fetch-tiktok-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install jq
        run: sudo apt-get install -y jq
        
      - name: Make API request
        run: |
          curl -v \
            -x ${{ secrets.PROXY_URL }} \
            -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15' \
            "https://www.tiktok.com/node/share/discover" | jq . > discover-sg.json || echo "Curl Failed."
        env:
          PROXY_URL: http://178.251.47.138:8080
          
      - name: Check if file was created
        run: |
          if [ -f discover-sg.json ]; then
            echo "File was created successfully"
            ls -l discover-sg.json
          else
            echo "File creation failed"
            exit 1
          fi
          
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add discover-sg.json
          git commit -m "Update TikTok discover data" || echo "No changes to commit"
          git push
